hmcts/azure-policy

.github/workflows/manage-azure-policy.yml
assignments/mg-dts002/assign.tagging.json
pipeline-scripts/sandbox-override.sh
policies/tagging/README.md
policies/tagging/policy.json

- Add pipeline for azure policies 
- Create initial policies
- As part of DTSPO-385 - the policy has been set to audit and the url check has been removed
```
[ ] Yes
[x] No
```

DTSPO-379 - add policy manager and initial policy and assignment

---

assignments/mg-dts002/assign.diagnostics.json

- Initial diagnostic policy commit
- Fix assign json error
- Fix assign json error
- Setting enforcement to doNotEnforce
- Adding managed identity
- Adding managed identity
- Add location to msi
- Moving msi block
- Move msi to assign json
- move msi outside properties block
- remove msi location
- Updating msi location to global
- testing with userassigned
- testing with userassigned
- Add location
- Revert to systemAssigned
- Parameterise event hub name and auth rule
- Fix json
- Fix json
- missing policy rules
- Adding allowed values
- updating auth rule name
- Revert parameter name change
- Missing parameters and naming changes
- Update enforcement mode
- Add diag readme
- Fix scope
- Updating scope uri to include mgmt group

DTSPO-5695 - Assignment scope URI update

---

.github/workflows/manage-azure-policy.yml

- Initial commit for subscription targeting
- Remove comliance check for subscription
- Remove matrix
- Update allow-no-subs key

DTSPO-6100 - fix actions error

---

.github/workflows/manage-azure-policy.yml
assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.diagnostics.json
assignments/subscriptions/8ae5b3b6-0b12-4888-b894-4cec33c92292/assign.diagnostics.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.diagnostics.json

- Initial commit for subscription targeting
- Remove comliance check for subscription
- Adding soc-prod subscription
Dependent on #15

DTSPO-5958 - Diagnostic policy prod

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.diagnostics.json
assignments/subscriptions/8ae5b3b6-0b12-4888-b894-4cec33c92292/assign.diagnostics.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.diagnostics.json

Will make it easier to identify managed identities﻿

DTSPO-5958 - renaming policy assignments

---

.github/workflows/manage-azure-policy.yml
README.md
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.diagnostics.json
pipeline-scripts/sandbox-override.sh

Update sandbox script to work with multiple subscription assignments so a pull request only attempts to assign a policy to DCD-CFTAPPS-SBOX﻿

DTSPO-5895 - update sandbox script

---

assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-5594
add enforced tagging policy for sds sandbox
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```

add enforced tagging policy for sds sandbox

---

assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json

https://github.com/hmcts/azure-policy/blob/d70c38df9a93e82c14a71ce71ed3991e836cafc1/assignments/mgmt-groups/mg-dts002/assign.tagging.json#L17-L18

DTSPO-5594 Exclude AKS

---

assignments/subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/assign.tagging.json

Created policy assignment for DTS-SHAREDSERVICES-PROD with enforcementMode set to Default (enforcing).
```
[ ] Yes
[x] No
```

DTSPO-5765 - creat tagging policy for sds prod and set to enforcing

---

README.md
assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json

https://tools.hmcts.net/jira/browse/DSTPO-6394
Testing policy assignment names with less than 24 characters
Seems to be a bug in the github action that requires this now
```
[ ] Yes
[x] No
```

DTSPO-6392 - Create diag policy for KeyVault -2

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json

https://tools.hmcts.net/jira/browse/DTSPO-6392
Test removing assignment name for keyvault policy assignment
```
[ ] Yes
[x] No
```

DTSPO-6392 - Create diag policy for KeyVault - 3

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json

Reverts hmcts/azure-policy#33
Previous PR was to test if assignment name would be automatically generated but this did not happen

Revert DTSPO-6392 - Create diag policy for KeyVault - 3

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json

https://tools.hmcts.net/jira/browse/DTSPO-6392
Update policy assignment id path for kv policy
```
[ ] Yes
[x] No
```

DTSPO-6392 - Create diag policy for KeyVault - 4

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json

https://tools.hmcts.net/jira/browse/DTSPO-6392
Fix policy assignment id path
Was previously copied from one using management group which has a character limit but for testing it needs to be the subscription instead
```
[ ] Yes
[x] No
```

DTSPO-6392 - Create diag policy for KeyVault - 5

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json

JIRA link (if applicable)
[tools.hmcts.net/jira/browse/DTSPO-6392](https://tools.hmcts.net/jira/browse/DTSPO-6392)
Change description
Pasted wrong subscription id into DCD-CFTAPPS-SBOX
Does this PR introduce a breaking change? (check one with "x")
[ ] Yes
[x] No

DTSPO-6392 - Create diag policy for KeyVault - 6

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json
policies/keyvault/policy.json

https://tools.hmcts.net/jira/browse/DSTPO-6392
Test using UAMI on keyvault policy and assignment for allowing access to soc eventhub
```
[ ] Yes
[x] No
```

DTSPO-6392 - Test UAMI on keyvault policy

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json

- donotenforce policy assignment for tagging on sandbox CFT environment
- adding notScopes with aks resource groups
```
[ ] Yes
[x ] No
```

DoNotEnforce Sandbox policy assignment

---

assignments/subscriptions/2307d175-7e49-434b-9ac2-515529b845f2/assign.keyvault.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.keyvault.json

https://tools.hmcts.net/jira/browse/DTSPO-6392
Update resource ID for uami following name change
```
[ ] Yes
[x] No
```

DTSPO-6392 - Update uami resource ID

---

policies/appgateway_diagnostics/policy.json

wrong role
```
[ ] Yes
[x] No
```

DTSPO-6396 Update role

---

assignments/mgmt-groups/mg-dts002/assign.appgateway_diagnostics.json
assignments/mgmt-groups/mg-dts002/assign.diagnostics.json
policies/appgateway_diagnostics/policy.json

DTSPO-6396 Rename + add uami 

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.tagging.json

We already have a policy assignment for subscription b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb (DCD-CFTAPPS-SBOX) ; DCD-CFT-Sandbox / bf308a5c-0624-4334-8ff8-8dca9fd43783 is also under CFT scope and we need an assignment for tagging for that subscription too.
```
[ ] Yes
[ x] No
```

DCD-CFT-Sandbox policy assignment

---

assignments/mgmt-groups/mg-dts002/assign.appgateway_diagnostics.json

https://tools.hmcts.net/jira/browse/DTSPO-6396
```
[ ] Yes
[x] No
```

DTSPO-6396 Change name of policy back

---

assignments/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/assign.tagging.json
assignments/subscriptions/8cbc6f36-7c56-4963-9d36-739db5d00b27/assign.tagging.json

DoNotEnforce policy assignment for prod, excluding aks node rg scope only.
```
[ ] Yes
[x ] No
```

policy assignment Prod

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.appgateway_diagnostics.json
policies/appgateway_diagnostics/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-6396
test assignment / getting the policy to actually work
```
[ ] Yes
[x] No
```

DTSPO-6396 Update App Gateway Policy and Test Assignment

---

assignments/mgmt-groups/mg-dts002/assign.postgresql_diagnostics.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_diagnostics.json
policies/postgresql_diagnostics/README.md
policies/postgresql_diagnostics/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-6401
```
[ ] Yes
[x] No
```

DTSPO-6401 Add PSQL Policy

---

assignments/mgmt-groups/mg-dts002/assign.postgresql_diagnostics.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_diagnostics.json
policies/postgresql_diagnostics/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-6401
Name was over 24 characters
```
[ ] Yes
[x] No
```

DTSPO-6401 Shorten name

---

policies/frontdoor/README.md

DTSPO-6398
Add ReadME file for Front Door Policy
```
[ ] Yes
[X] No
```

DTSPO-6398 - Add ReadME file for Front Door Policy

---

assignments/mgmt-groups/mg-dts002/assign.postgresql_flexible_diagnostics.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_flexible_diagnostics.json
policies/postgresql_flexible_diagnostics/README.md
policies/postgresql_flexible_diagnostics/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-6402
```
[ ] Yes
[x] No
```

DTSPO-6402 Add PSQL Flexible Policy

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.tagging.json

Enforcement Mode is set to Default. See impact on sanbox:
https://docs.microsoft.com/en-us/azure/governance/policy/concepts/assignment-structure#enforcement-mode
```
[ ] Yes
[x ] No
```

enforce tagging policy on sanbox

---

assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json

Fix Jenkins builders
```
[ ] Yes
[X] No
```

Fix Jenkins builders

---

policies/tagging/policy.json

DTSPO-8723: Add "preview" in allowed  environment list

---

assignments/subscriptions/8b6ea922-0862-443e-af15-6056e1c9b9a4/assign.tagging.json

DTSPO-8710.  disable tagging in cft-dev

---

assignments/subscriptions/1497c3d7-ab6d-4bb7-8a10-b51d03189ee3/assign.tagging.json

Revert "Fix Jenkins builders"

---

assignments/mgmt-groups/mg-dts002/assign.tagging.json
assignments/subscriptions/3eec5bde-7feb-4566-bfb6-805df6e10b90/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-9094
```
[ ] Yes
[ ] No
```

DTSPO-9094 Move exclusion for AzureBackupRG_uksouth_1

---

assignments/subscriptions/61432c17-4377-4780-be02-d56e56ef2b07/assign.tagging.json
assignments/subscriptions/cad00ede-36df-4e04-ad0b-d34a1e94ef76/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-9361
Added tagging policy assignments for new archiving subscriptions.
```
[ ] Yes
[ x ] No
```

feat: add assignments for archiving subs

---

assignments/subscriptions/61432c17-4377-4780-be02-d56e56ef2b07/assign.autotagging-application.json
assignments/subscriptions/61432c17-4377-4780-be02-d56e56ef2b07/assign.autotagging-businessarea.json
assignments/subscriptions/61432c17-4377-4780-be02-d56e56ef2b07/assign.autotagging-environment.json
assignments/subscriptions/cad00ede-36df-4e04-ad0b-d34a1e94ef76/assign.autotagging-application.json
assignments/subscriptions/cad00ede-36df-4e04-ad0b-d34a1e94ef76/assign.autotagging-businessArea.json
assignments/subscriptions/cad00ede-36df-4e04-ad0b-d34a1e94ef76/assign.autotagging-environment.json

https://tools.hmcts.net/jira/browse/DTSPO-9361
Fix name miss-match in policy assignments 
```
[ ] Yes
[ x ] No
```

fix: name missmatch with autotagging assignments

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.autotagging.json

fix: corrected issues with sandbox assignment

---

assignments/subscriptions/cad00ede-36df-4e04-ad0b-d34a1e94ef76/assign.autotagging-environment.json

https://tools.hmcts.net/jira/browse/DTSPO-9361
```
[ ] Yes
[ x ] No
```

fix: issue with autotagging wrong environment

---

policies/tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-10071
Add Azure Policy exception for Azure Private DNS Resolver Endpoints
```
[ ] Yes
[ ] No
```

Add Azure Policy exception for Azure Private DNS Resolver Endpoints

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
policies/tagging/policy-old-mg.json

DTSPO-9918
Create new tagging assignment for HMCTS MG
```
[ ] Yes
[X] No
```

DTSPO-9918 - Create new tagging assignment for HMCTS MG

---

policies/appgateway_diagnostics/policy-old-mg.json
policies/appgateway_diagnostics/policy.json
policies/autotagging/policy-old-mg.json
policies/diagnostics/policy-old-mg.json
policies/frontdoor/policy-old-mg.json
policies/keyvault/policy-old-mg.json
policies/keyvault/policy.json
policies/nsg_diagnostics/policy-old-mg.json
policies/nsg_diagnostics/policy.json
policies/postgresql_diagnostics/policy-old-mg.json
policies/postgresql_diagnostics/policy.json
policies/postgresql_flexible_diagnostics/policy-old-mg.json

DTSPO-9918
Create policies for HMCTS MG
```
[ ] Yes
[X] No
```

DTSPO-9918 - Create policies for HMCTS MG

---

assignments/mgmt-groups/mg-HMCTS/assign.appgateway_diagnostics.json
assignments/mgmt-groups/mg-HMCTS/assign.diagnostics.json
assignments/mgmt-groups/mg-HMCTS/assign.frontdoor.json
assignments/mgmt-groups/mg-HMCTS/assign.keyvault.json
assignments/mgmt-groups/mg-HMCTS/assign.nsg_diagnostics.json
assignments/mgmt-groups/mg-HMCTS/assign.postgresql_diagnostics.json
assignments/mgmt-groups/mg-HMCTS/assign.postgresql_flexible_diagnostics.json

DTSPO-9918
Create policy assignments for HMCTS MG
```
[ ] Yes
[X] No
```

DTSPO-9918 - Create assignments for HMCTS MG

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits.json
assignments/mgmt-groups/mg-dts002/assign.azuresql_audits.json

https://tools.hmcts.net/jira/browse/DTSPO-9968
Azure SQL policy assignment. 
```
[ ] Yes
[ ] No
```

DTSPO-9968: Azure SQL Policy assignment

---

policies/tagging/policy.json

excluded flowlogs

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-dts002/assign.tagging.json
policies/tagging-OLD-MG/README.md
policies/tagging-OLD-MG/policy.json

Dtspo 9009 adding enforcement mode default

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-dts002/assign.tagging.json

Revert back enforecement mode for Tagging

---

policies/tagging-OLD-MG/policy.json
policies/tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-9009
Dtspo 9017 - Add VNET Link Tagging Exclusion
```
[ ] Yes
[X] No
```

Added VNET Link Tagging Exclusion

---

assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json

assigned enforcement to DTS-HERITAGE-INTSVC-STG

---

assignments/mgmt-groups/mg-dts002/assign.tagging.json
assignments/subscriptions/17390ec1-5a5e-4a20-afb3-38d8d726ae45/assign.tagging.json
assignments/subscriptions/9c604868-4643-43b8-9eb1-4c348c739a3e/assign.tagging.json
assignments/subscriptions/c170c61a-f00f-4295-a718-634e27af1597/assign.tagging.json

Tagging to Enforce toall the Heritage Subscription

---

assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json

inserted martha-rg in exception temporarily

---

assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json

added back Martha-rg

---

.github/workflows/manage-azure-policy.yml

The list of subs is broken as the structure has changed. This should fix the subscription list and will find any subscriptions as long as they're under the HMCTS MG
```
[ ] Yes
[x] No
```

DTSPO-9985 - fix subscription search

---

assignments/subscriptions/61432c17-4377-4780-be02-d56e56ef2b07/assign.autotagging-businessarea.json
assignments/subscriptions/cad00ede-36df-4e04-ad0b-d34a1e94ef76/assign.autotagging-businessArea.json

feat: tweaked ARM tagging policy to match common tags

---

policies/tagging/README.md

see https://github.com/hmcts/azure-policy/blob/d28ccc2c503bfaccf147441af30d05ee7d8653ec/policies/tagging/policy.json#L47

Correct case of business area tag in docs

---

assignments/subscriptions/17390ec1-5a5e-4a20-afb3-38d8d726ae45/assign.tagging.json
assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json
policies/tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-11753
Add the 4 VMs to noScope to enable backups to run
```
[ ] Yes
[ X] No
```

Add_VMs-to-ignore

---

policies/tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-11753
Allow VMs to create snapshots for backups to be taken from
```
[ ] Yes
[ X] No
```

Allow-Microsoft.Compute/snapshots

---

assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json

Same as https://github.com/hmcts/azure-policy/pull/127

Ignore data migration rg

---

assignments/mgmt-groups/mg-cft-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json
policies/expires-after-tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-11786
Changing effect from audit to deny. 
```
[ ] Yes
[x] No
```

DTSPO-11786-Set-expiresAfter-policy-into-enforce-mode

---

policies/expires-after-tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-11786
Adding resource exclusions 
```
[ ] Yes
[x] No
```

adding exclusions

---

assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-12507
Disable tagging on AAT DefStore RG
```
[ ] Yes
[ x] No
```

Disable tagging on AAT DefStore RG

---

assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.changetracking.json

added missing parameters

---

assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.changetracking.json

removed parameter

---

assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.changetracking.json

Test3 changetracking policy

---

assignments/subscriptions/1fe7db01-9981-4ed3-983c-163dd50ba43a/assign.tagging.json

Adding exception for Alex Gudgeon resource group
```
[ ] Yes
[X ] No
```

adding sbox exception for Alex Gudgeon

---

policies/tagging/policy.json

add resource Microsoft.Powershell.DSC to excludedResourceTypes policy
```
[ ] Yes
[X] No
```

add resource Microsoft.Powershell.DSC to excludedResourceTypes policy

---

policies/tagging/policy.json

Tagging policy still blocking with current - attempting resourceType Microsoft.Compute/virtualMachines/extensions

Test with Microsoft.Compute/virtualMachines/extensions exclusion

---

assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json

Testing-removed tagging requirement for martha resource group

---

assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json

Removed martha from not scope

---

assignments/mgmt-groups/mg-cft-sandbox/assign.azuresql_audits_ukw.json

Updating UKW assignment policy id and managed id
```
[ ] Yes
[x] No
```

update ukw assignment policy id & managed id

---

assignments/mgmt-groups/mg-cft-sandbox/assign.azuresql_audits_ukw.json

Update user assigned policy
```
[ ] Yes
[x] No
```

updating user assigned identity

---

assignments/mgmt-groups/mg-cft-sandbox/assign.azuresql_audits_ukw.json

updating user assigned identity
```
[ ] Yes
[x ] No
```

updating the userassign identity

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_ukw.json

Updating resource group for UKW assignment 
```
[ ] Yes
[ x] No
```

updating subscription for eventhub rule assignment

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_ukw.json

updating the subscription id on user assigned identity for ukw prod
```
[ ] Yes
[x] No
```

update subscription id on user assigned identity

---

assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json

adding hackathon rg to notscopes

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_ukw.json

Changing assignment name for ukw, cant seem to find. To keep it short adding an additional letter. Assignment with same name already existed
```
[ ] Yes
[ ] No
```

DTSPO-11338: Change policy assignment name

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_ukw.json

Keeping a descriptive name at the 24 characters limit
```
[ ] Yes
[ ] No
```

DTSPO-11338: limiting to 24 characters max

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_ukw.json

Fixing errors by updating the managed identity name to correct value
```
[ ] Yes
[ ] No
```

DTSPO-11338: Update to manage identity value

---

assignments/mgmt-groups/mg-cft-sandbox/assign.locationpolicy.json
policies/allowed_regions/README.md
policies/allowed_regions/policy.json

Adds a policy to restrict the ability to create resources in other regions other then UK South and Global
```
[ ] Yes
[X] No
```

Creates a policy for restricting locations to UK South

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_regions.json

Rename assignment file name, fixes naming in assignment
```
[ ] Yes
[X] No
```

Rename assignment file name, fixes naming in assignment

---

policies/allowed_regions/policy.json

Adds strongType to parameter
```
[ ] Yes
[X] No
```

Adds strongType to parameter

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

Missed path changed when moving from Sandbox
```
[ ] Yes
[X] No
```

Fix missed path typo

---

policies/allowed_regions/README.md

Update README file for location policy
```
[ ] Yes
[X] No
```

Updates README file

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

Adding exemptions for some missing RG's for video hearings.
```
[ ] Yes
[X] No
```

Add exemptions for some missed RG's

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

https://tools.hmcts.net/jira/browse/DTSPO-12835
Adds exemption for palo RG's in UK West
```
[ ] Yes
[X] No
```

Adds exemption for palo RG's in UK West

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json
assignments/mgmt-groups/mg-HMCTS/assign.tagging.json

added b2c resource group to exception

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

allow pre-sbox-backup RG for ukw storage accounts
```
[ ] Yes
[X] No
```

Storage ukw

---

assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json

add postgres migration RG 

---

assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json

add ccd data store rg in  exemption list

---

policies/expires-after-tagging/policy.json
policies/tagging/policy.json

DTSPO-13493
Stop tagging policy blocking new AVDs being deployed 
```
[ ] Yes
[ X] No
```

Exclude Tags For PowerShell DSC

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
policies/expires-after-tagging/policy.json
policies/tagging/policy.json

DTSPO-13493
Allow Microsoft.Resources/deployments on tagging policy
```
[ ] Yes
[X ] No
```

Allow-Microsoft.Resources/deployments

---

assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json
assignments/subscriptions/1497c3d7-ab6d-4bb7-8a10-b51d03189ee3/assign.tagging.json
assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json
assignments/subscriptions/64b1c6d6-1481-44ad-b620-d8fe26a2c768/assign.tagging.json
assignments/subscriptions/6c4d2513-a873-41b4-afdd-b05a33206631/assign.tagging.json
assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json
assignments/subscriptions/ba71a911-e0d6-4776-a1a6-079af1df7139/assign.tagging.json

Exclude Resource group related to DMS tool

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

Adding sbox shutter page to region exclusion list

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_vm_sku.json
policies/allowed_vm_sku/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-13650
Creating a policy to restrict VM SKU Sizes 
```
[ ] Yes
[x ] No
```

adding vm sku size policy

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_vm_sku.json
policies/allowed_vm_sku/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-13650
Updating policy to ensure the usage of specified vm sku sizes
```
[ ] Yes
[x ] No
```

updated parameter name

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_vm_sku.json
policies/allowed_vm_sku/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-13650
updated policy description and added virtual machine contributor role to the DCD-CFT-Sandbox subscription.
```
[ ] Yes
[x ] No
```

update access policy azure & description

---

policies/allowed_vm_sku/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-13650
Updating policy logic to allow specified vm sizes
```
[ ] Yes
[x] No
```

updating policy logic

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

Adding Neil's test RG

---

policies/allowed_regions/policy.json

Exclude cdn end points from location policy

---

policies/allowed_vm_sku/README.md

https://tools.hmcts.net/jira/browse/DTSPO-13978
updating the exemptions link
```
[ ] Yes
[x ] No
```

updated exemptions list link

---

assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json

Exclude a RG to cover servicebus integration with logic app

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

https://tools.hmcts.net/jira/browse/DTSPO-11118
including panorama resource groups to add kev vault secrets for panorama alerts email server profile
```
[ ] Yes
[x ] No
```

adding panorama rg

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

allow old SKU in VH TEST env
```
[ ] Yes
[X] No
```

allow old SKU in VH TEST env

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

Add missing comma
```
[ ] Yes
[X] No
```

Add missing comma

---

.github/workflows/blank.yml

Triggered by https://github.com/hmcts/azure-policy/pull/233
and https://tools.hmcts.net/jira/browse/DTSPO-14170

Lint JSON files

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

ignore rg for creating a static web app as part of poc

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

ignore static webapp resource rg in sbox env

---

assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json
assignments/subscriptions/8999dec3-0104-4a27-94ee-6588559729d1/assign.tagging.json
assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.tagging.json

Management group appears to be only in detect mode.
Policy is applied at individual subscription level =/

Copy policy exclusions to sub

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

DTSPO-14285 add static webapp rg

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

exclude shutter webapp Resource group for PROD env

---

assignments/mgmt-groups/mg-cft-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json

Switched bad links from azure incomplete tagging message
```
[ ] Yes
[x] No
```

borked snake case links switched to kebab case

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json
policies/allowed_regions/README.md

https://tools.hmcts.net/jira/browse/DTSPO-14826
Adds exemptions to policy to remove all infra in subs, will revert once all infra has been removed from subs
```
[ ] Yes
[X] No
```

Adds exemptions to policy to remove all infra in subs

---

assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-14926
This is only for test purpose this will be removed after test. The resources need to be excluded from policy deny effects for normal operation.
```
[ ] Yes
[x ] No
```

Exclude Resoure Group from policy for Azure SQL instance

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json
assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json
assignments/subscriptions/a8140a9e-f1b0-481f-a4de-09e2ee23f7ab/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-14926
Exclude SQL MI Test RG
```
[ ] Yes
[x] No
```

feat: exclude whole rg while testing

---

assignments/subscriptions/6c4d2513-a873-41b4-afdd-b05a33206631/assign.tagging.json

Exclude Jenkins vm rg from policy

---

assignments/mgmt-groups/mg-cft-sandbox/assign.expiresaftertag.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json

Excluded resource group to test the deployment of premium front door.
```
[ ] Yes
[ X] No
```

excluded resource group to test

---

policies/expires-after-tagging/policy.json

[DTSPO-13992](https://tools.hmcts.net/jira/browse/DTSPO-13992)
migration is failing due to policy, adding exclusion for front door classic
```
[ ] Yes
[x] No
```

DTSPO-13992-add exclusion for front door

---

assignments/mgmt-groups/mg-cft-sandbox/assign.expiresaftertag.json

https://tools.hmcts.net/jira/browse/DTSPO-14200
adding an exception for sbox for apim

adding exception on sandbox for apim

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

DFR-2320 
Add div-aat exclusion for Uk South region check (AppInsights)

DFR-2320: Add div exclusion

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-cft-sandbox/assign.expiresaftertag.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-15146
Excluding frontdoor non-prod resource groups from having enforced tagging policy for migration.
- [ X] commit messages are meaningful and follow good commit message guidelines

DTSPO-15146 - removed sbox and added non-prod envs

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json

https://tools.hmcts.net/jira/browse/DTSPO-13993
turning off policies to migrate nonprod sds frondoors
- [ X] commit messages are meaningful and follow good commit message guidelines

turning off policies to migrate nonprod sds fd

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

Add West Europe location exception for RD

---

assignments/mgmt-groups/mg-HMCTS/assign.copy.rg.required.tags.json
assignments/mgmt-groups/mg-cft-sandbox/assign.copy.expireafter.tag.json
assignments/mgmt-groups/mg-platform-sandbox/assign.copy.expireafter.tag.json
assignments/mgmt-groups/mg-sds-sandbox/assign.copy.expireafter.tag.json

https://tools.hmcts.net/jira/browse/DTSPO-15352
Rolling out new policy to the management groups.

DTSPO-15352 - rollout copy policy to management gp

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json

exclude rg from hmcts policy

---

assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json

whitelist resource group from hmcts policy

whitelist resource group from policy

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json

https://tools.hmcts.net/jira/browse/DTSPO-16045
adding exemption to build poc for ngfw

updating exemption for ngfw poc rg

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json

https://tools.hmcts.net/jira/browse/DTSPO-16045
reverting the exemption for the NGFW POC

revert exemption for poc to test rg

---

assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json

adding policy exemption for oz-rg lab

add policy exemption for oz-rg lab

---

assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json

adding exemption for tagging for nd lab

add exemptions for tagging and expires after

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json
assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

excluding all the subs from these two policies

Chore crime sub exclusion

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

https://tools.hmcts.net/jira/browse/DTSPO-15909
Adding resource group as exception to complete the app insight migration

add div-sandbox as exception

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.frontdoor.json
policies/frontdoor/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-16185
Updated api version and resource name to pick up premium frontdoors in policy

Updated api version and changed resource type

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

DTSPO-15909
adding exceptions for bar app insights migration

adding exceptions for bar app insights migration

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json

DTSPO-15909
Adding temp tag exclusions for app insights migration. App Insights module will add missing default tags.

DTSPO-15909 - current resources have no tags, module will add common tags

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json

Dtspo 15909 
adding exclusion for aat / demo

Dtspo 15909 - adding exclusion for aat / demo

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json
assignments/subscriptions/7a4e3bd5-ae3a-4d0c-b441-2188fee3ff1c/assign.tagging.json

Dtspo 15909
Adding exclusions for aat and perf test

Dtspo 15909 - Adding exclusions for aat and perf test 

---

README.md

n/a
Added a section to the README to explain how to rotate the clientSecret value stored in AZURE_CREDENTIALS

Updated readme to include section on rotating AZURE_CREDENTIALS secret

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json
assignments/subscriptions/7a4e3bd5-ae3a-4d0c-b441-2188fee3ff1c/assign.tagging.json

DTSPO-15909
Removing bar shared infrastructure exclusions for App Insights following migration.

DTSPO-15909 - Removing bar shared infrastructure exclusions for App Insights

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json

whitelist new rg for chatbot testing

add new rg for whitelist

---

assignments/subscriptions/867a878b-cb68-4de5-9741-361ac9e178b6/assign.purview.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.purview.json
policies/purview/README.md
policies/purview/policy.json

https://tools.hmcts.net/jira/browse/DC-206
https://tools.hmcts.net/jira/browse/CYBER-8771
Add a policy to force Purview to send logs to the soc event hub

Add config for Purview to auto send logs to the soc event hub

---

policies/purview/policy.json

https://tools.hmcts.net/jira/browse/DC-206
Update incorrect template for Purview policy

Update purview policy template

---

assignments/subscriptions/867a878b-cb68-4de5-9741-361ac9e178b6/assign.purview.json

https://tools.hmcts.net/jira/browse/DC-206
Add Azure Policy assignment for Purview in dts-sharedservices-dev

Add Azure Policy assignment for Purview in dts-sharedservices-dev

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json

adding new rg to the list for tagging purposes

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json

removing the resource group

---

assignments/subscriptions/b44eb479-9ae2-42e7-9c63-f3c599719b6f/assign.aum_scanning.json
policies/update_manager_scans/README.md
policies/update_manager_scans/example_policy.json.txt
policies/update_manager_scans/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-16824
Azure policy to enable Azure Update Manager scanning on VMs by subscription

Dtspo 16824 azure update manager policies

---

assignments/mgmt-groups/mg-HMCTS/assign.aum_scan.json

https://tools.hmcts.net/jira/browse/DTSPO-16824
Create an Azure policy to enable Azure Update manager scans for missing patches.  Select VMs based on TAGs assigned to VMs

Scan-Windows-VMs-in-HMCTS-tagged

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json

Reverts hmcts/azure-policy#334

Revert "DTSPO-16138 - Temporary exclude for tagging cvp sbox rg"

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

https://tools.hmcts.net/jira/browse/DTSPO-17635
Add test resourcegroup to notScopes.
Testing the changes I've made to the template

DTSPO-17635 - Add notScope

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

https://tools.hmcts.net/jira/browse/DTSPO-17635
Allow vm SKUs on test resource group so change from premium to standard disks can be tested

DTSPO-17635 - Allow SKUs on test resource group

---

assignments/mgmt-groups/mg-HMCTS/assign.vpn.json
policies/vpn/README.md
policies/vpn/policy.json

exclude vnet via subscription

---

assignments/mgmt-groups/mg-cft-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-platform-sandbox/assign.expiresaftertag.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.tagging.json

no jira link
removing lab exemptions from practise lab.

removing rsi lab exemptions

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

https://tools.hmcts.net/jira/browse/DTSPO-17635
Remove test resource group from exclusion
Tests have been completed

DTSPO-17635 - remove test resource group from exclusion

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_servicebus_sku.json

https://tools.hmcts.net/jira/borwse/DTSPO-18398
Fix typo in scope

DTSPO-18398 - Fix scope typo

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_servicebus_sku.json

https://tools.hmcts.net/jira/borwse/DTSPO-18398
Fix typo in id

DTSPO-18398 - Fix id typo

---

policies/allowed_servicebus_sku/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-18398
Remove policyrule section that was copied from disk policy
Not needed

DTSPO-18398 - Remove policyRule

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_servicebus_sku.json

https://tools.hmcts.net/jira/browse/DTSPO-18398
Assign service bus policy to HMCTS MG
Tested on CFT - Sandbox
Doesn't allow premium in Sandbox but does in non-Sandbox during testing

DTSPO-18398 - Assign to HMCTS MG

---

assignments/mgmt-groups/mg-cft-sandbox/assign.allowed_redis_sku.json
policies/allowed_redis_sku/README.md
policies/allowed_redis_sku/policy.json

[DTSPO-18397](https://tools.hmcts.net/jira/browse/DTSPO-18397)
Create policy to limit redis cache SKUs to basic and standard in nonprod

DTSPO-18397 Create redis cache policy

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json

whitelist perf test and datalake RG to add tag on VM for autoshutdown 
removed unwanted whitelist of RG

whitelist perf test and datalake RG

---

policies/tagging/policy.json

add vm resource to tagging policy exclusion list temporarily

add vm resource to tagging policy exclusion list temporarily

---

policies/tagging/policy.json

revert vm polcy temporary changes to add tag for auto shutdown

revert vm policy changes

---

pipeline-scripts/sandbox-override.sh

Adding additional step to create sandbox management group assignments for testing purposes

Adding additional step to create sandbox management group assignments for testing purposes

---

assignments/mgmt-groups/mg-HMCTS/assign.keyvault_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault_diagnostics_moj.json
policies/keyvault/policy.json

See [DTSPO-18607](https://tools.hmcts.net/jira/browse/DTSPO-18607)
fix issue with name length and revert old policy name

fix issue with assignment name length and revert policy name

---

policies/keyvault/policy.json

See [DTSPO-18607](https://tools.hmcts.net/jira/browse/DTSPO-18607)
remove duplicate add extra value

remove duplicate and add extra allowed value

---

assignments/mgmt-groups/mg-HMCTS/assign.diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.diagnostics_moj.json
policies/diagnostics/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-18608
Adding parameters to subscription level diagnostic policy, adding a sandbox assignment to test

Adding parameters to subscription level diagnostic policy, adding a sandbox assignment to test

---

assignments/mgmt-groups/mg-HMCTS/assign.postgresql_flexible_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_flexible_diagnostics_moj.json
policies/postgresql_flexible_diagnostics/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-18611
Updating PSQL Flex policy for better display name and adding assignments for MOJ eventHub

Updating PSQL Flex policy for better display name and adding assignments for MOJ eventHub

---

assignments/mgmt-groups/mg-HMCTS/assign.frontdoor_diagnostics_moj.json

See [DTSPO-18609](https://tools.hmcts.net/jira/browse/DTSPO-18609)
Fix typo on assignment name

fix issue with assignment name

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

https://tools.hmcts.net/jira/browse/DTSPO-18811
Updating exclusions to allow changes to be made to perftest keyvault which is in Central US region.
Not currently able to add myself in the access policy because of this.
Needed so I can troubleshoot and fix the pipeline for this ticket.

DTSPO-18811 - Update exclusions for perftest resource group

---

assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-18811
Updating exclusions to allow changes to be made to perftest keyvault.
Not currently able to add myself in the access policy because of this.
Needed so I can troubleshoot and fix the pipeline for this ticket.

DTSPO-18811 - Add tagging exclusion to perftest keyvault

---

policies/expires-after-tagging/policy.json
policies/tagging/policy.json

Resource exemption required one expired tagging policy

Resource exemption required one expired tagging policy

---

assignments/mgmt-groups/mg-HMCTS/assign.appgateway_diagnostics_moj.json
assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_diagnostics_moj.json
assignments/mgmt-groups/mg-HMCTS/assign.diagnostics_moj.json
assignments/mgmt-groups/mg-HMCTS/assign.frontdoor_diagnostics_moj.json
assignments/mgmt-groups/mg-HMCTS/assign.keyvault_diagnostics_moj.json
assignments/mgmt-groups/mg-HMCTS/assign.postgresql_diagnostics_moj.json
assignments/mgmt-groups/mg-HMCTS/assign.postgresql_flexible_diagnostics_moj.json
assignments/mgmt-groups/mg-cft-sandbox/assign.postgresql_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.appgateway_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.azuresql_audits_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.frontdoor_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_flexible_diagnostics_moj.json
policies/appgateway_diagnostics/policy.json
policies/azuresql_audits/policy.json
policies/diagnostics/policy.json
policies/frontdoor/policy.json
policies/keyvault/policy.json
policies/postgresql_diagnostics/policy.json
policies/postgresql_flexible_diagnostics/policy.json

Migrate XSIAM eventhub names

---

assignments/mgmt-groups/mg-HMCTS/assign.keyvault_diagnostics_mojTEST.json

Test new KV

---

assignments/mgmt-groups/mg-HMCTS/assign.keyvault_diagnostics_mojTEST.json

Test new KV ID

---

assignments/mgmt-groups/mg-HMCTS/assign.keyvault_diagnostics_moj.json
policies/keyvault/policy.json

New policy to check eventhub name

---

policies/keyvault/policy.json

Was added in https://github.com/hmcts/azure-policy/pull/393
But wasn't inside the allow list

Add sender policy to allow list

---

assignments/mgmt-groups/mg-HMCTS/assign.postgresql_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.postgresql_diagnostics_moj.json
policies/postgresql_diagnostics/policy.json

Update authrule for postgresql

---

assignments/mgmt-groups/mg-HMCTS/assign.appgateway_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.appgateway_diagnostics_moj.json
policies/appgateway_diagnostics/policy.json

Update policy for appgateway diagnostics

---

assignments/mgmt-groups/mg-HMCTS/assign.azuresql_audits_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.azuresql_audits_diagnostics_moj.json
policies/azuresql_audits/policy.json

Update policy for azuresql audits diagnostics

---

assignments/mgmt-groups/mg-HMCTS/assign.frontdoor_diagnostics_moj.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.frontdoor_diagnostics_moj.json
policies/frontdoor/policy.json

Update policy for moj frontdoor

---

assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json

Tagging policy relaxed for subresource creation

Adding exceptions to allow playwrite for SSCS

---

assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json

made an error in last commit, didnt add expected change

Adding exeptions to allow playwrite

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json
assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json

Enabling the SSCS teat with Playwright poc

 Update policy for allowed tags and region

---

policies/postgresql_diagnostics/policy.json

Add missing allowed values for postgresql diagnostics policy

---

.github/workflows/manage-azure-policy.yml

See [PROJ-18712](https://tools.hmcts.net/jira/browse/DTSPO-18712)
Adding a check to ensure only enabled subscriptions are run through the Compliance Check. Disabled subscriptions cause the Github Action to fail.
Tested locally to ensure it was returning enabled subscriptions.

Adding check for disabled subscriptions

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_disk_sku.json

https://tools.hmcts.net/jira/browse/DDMU-303
Raising this change as we require to create a shared disk that can be mounted to 9 of our virtual machines, and the current limit of a 2TB disk only allows us to connect it to 5 virtual machines, see platops help ticket for further info 
https://tools.hmcts.net/jira/browse/DTSPO-23474

DDMU-303-Darts-Shared-Disk

---

assignments/mgmt-groups/mg-HMCTS/assign.vpn.json

DTSPO-23913
removing exclusion on live sub for Atlassian

DTSPO-23913 - removing exclusion on live sub for Atlassian

---

assignments/subscriptions/d24c931e-2e6d-4508-8583-85ac42715580/assign.nsg_diagnostics_glimr-rg-dev.json

https://tools.hmcts.net/jira/browse/DTSPO-27183
- Updated Event hub vallue
- Updated scope to target correct resource group

DTSPO-27183 - Updated event hub value for glimr

---

assignments/mgmt-groups/mg-cft-sandbox/assign.aks.aad_admin_groups.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.deploy_policy_addon.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.disable_local_auth.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.nodeos_autoupgrade.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.planned_maintenance.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.policy_addon_enabled.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.use_managed_identities.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.workload_identity.json

See [DTSPO-27300](https://tools.hmcts.net/jira/browse/DTSPO-27300)
Create required AuditMode policies and assign to sandbox 

feat: add more aks policies to sandbox clusters

---

assignments/mgmt-groups/mg-cft-sandbox/assign.aks.aad_admin_groups.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.deploy_policy_addon.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.planned_maintenance.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.policy_addon_enabled.json

See [DTSPO-27300](https://tools.hmcts.net/jira/browse/DTSPO-27300)
Reduce character size of policy names under 24 chars and add missing fields

fix: reduce policy assignment name to under 24 chars and correct syntax

---

assignments/mgmt-groups/mg-cft-sandbox/assign.aks.allowed_apparmor_profiles.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.allowed_capabilities.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.liveness_readiness_probes.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_forbidden_sysctls.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_host_pid_ipc.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_latest_tag.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.prestop_hook.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.resource_limit_max.json

See [DTSPO-27228](https://tools.hmcts.net/jira/browse/DTSPO-27228)
Adds more sbox cluster polciies in audit mode

chore: add more aks policies to sbox

---

assignments/mgmt-groups/mg-cft-sandbox/assign.aks.allowed_apparmor_profiles.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.allowed_capabilities.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.liveness_readiness_probes.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_forbidden_sysctls.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_host_pid_ipc.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_latest_tag.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.prestop_hook.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.resource_limit_max.json

See [DTSPO-27228](https://tools.hmcts.net/jira/browse/DTSPO-27228)
Removes noncompliant message from policies

chore: remove noncompliant message

---

assignments/mgmt-groups/mg-cft-sandbox/assign.aks.allowed_apparmor_profiles.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_forbidden_sysctls.json

See [DTSPO-27228](https://tools.hmcts.net/jira/browse/DTSPO-27228)
rename param name and add forbidden sysctls

fix: rename param name and add forbidden sysctls

---

assignments/mgmt-groups/mg-HMCTS/assign.restrict_flex_volume_drivers.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_host_path_volume_paths.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_proc_mnt_types.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_pull_policy.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_read_only_root_fs.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_seccomp_profiles.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_selinux_options.json
assignments/mgmt-groups/mg-HMCTS/assign.restrict_user_and_group_ids.json

https://tools.hmcts.net/jira/browse/DTSPO-27229
- Move **Audit mode** security policies to wider HMCTS group to see if there are more non-compliance issues in rest of the environments. Next steps will be to enforce (deny/deployifnotexists) the ones that are found to be compliant everywhere (if any) to non-prod to double check no issues then (if still no issues) enforce in prod, also create story/action to address non-compliance for the rest.
Already run in Sandbox subscription and sandbox management group.

Move audit-mode security policies from Sbox MG to HMCTS MG to see if more compliance issues present

---

assignments/mgmt-groups/mg-cft-sandbox/assign.aks.allowed_capabilities.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.liveness_readiness_probes.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.no_host_pid_ipc.json
assignments/mgmt-groups/mg-cft-sandbox/assign.aks.prestop_hook.json

See [DTSPO-27228](https://tools.hmcts.net/jira/browse/DTSPO-27228)
Polishes aks policies
- excludes admin and system namespaces on allowed capabilities policy
- excludes multiple admin/system NS to readiness/liveness probe check and no host PID check
- Disables pre-hook test for now as mostly everything is failing this. Pre-hook doesn't seem like a widely used feature and only a handful of third party helm charts enable it.

chore: add exemptions to aks policies

---

assignments/mgmt-groups/mg-HMCTS/assign.aks.host_network_ports.json

- GH action failed as policy name was greater than 24 chars

Reducing length of policy name to pass checks

---

assignments/mgmt-groups/mg-HMCTS/assign.restrict_pull_policy.json

https://tools.hmcts.net/jira/browse/DTSPO-27229
Fix typo in the namespace exclusion `ipdam` should be `ipam`

Fix typo "ipdam" to "ipam" in the excluded namespace for pull policy

---

assignments/mgmt-groups/mg-HMCTS/assign.aks.allowed_external_ips.json
assignments/mgmt-groups/mg-HMCTS/assign.aks.block_naked_pods.json

https://tools.hmcts.net/jira/browse/DTSPO-27230
- Setting compliant policy assignments to `Deny` mode

Set policy effect to deny

---

assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_not_allow_con_esc.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_not_cap_sys_admin.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_not_host_process.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_not_use_csi.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_not_use_sec_cap.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_only_https.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_win_cpu_memory.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_win_not_con_admin.json
assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_win_only_user_group.json

[DTSPO-27231](https://tools.hmcts.net/jira/browse/DTSPO-27231)
Make corrections to fix errors

DTSPO-27231 - Make corrections to fix errors

---

assignments/mgmt-groups/mg-cft-sandbox/assign.k8s_win_only_user_group.json

https://tools.hmcts.net/jira/browse/DTSPO-27231
add ContainerUser to allowedUserNames

DTSPO-27231 - add ContainerUser to allowedUserNames

---

assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_not_allow_con_esc.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_not_cap_sys_admin.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_not_host_process.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_not_use_csi.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_not_use_sec_cap.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_only_https.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_win_cpu_memory.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_win_not_con_admin.json
assignments/mgmt-groups/mg-cft-nonprod/assign.k8s_win_only_user_group.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_not_allow_con_esc.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_not_cap_sys_admin.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_not_host_process.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_not_use_csi.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_not_use_sec_cap.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_only_https.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_win_cpu_memory.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_win_not_con_admin.json
assignments/mgmt-groups/mg-sds-nonprod/assign.k8s_win_only_user_group.json

[DTSPO-27231](https://tools.hmcts.net/jira/browse/DTSPO-27231)
Apply policies to nonprod that have already been applied to sandbox

DTSPO-27231 - Apply policies to nonprod that have already been applied to sandbox
