assignments/mg-dts002/assign.diagnostics.json

- Initial diagnostic policy commit
- Fix assign json error
- Fix assign json error
- Setting enforcement to doNotEnforce
- Adding managed identity
- Adding managed identity
- Add location to msi
- Moving msi block
- Move msi to assign json
- move msi outside properties block
- remove msi location
- Updating msi location to global
- testing with userassigned
- testing with userassigned
- Add location
- Revert to systemAssigned
- Parameterise event hub name and auth rule
- Fix json
- Fix json
- missing policy rules
- Adding allowed values
- updating auth rule name
- Revert parameter name change
- Missing parameters and naming changes
- Update enforcement mode
- Add diag readme
- Fix scope

DTSPO-5695 - sbox diag policy scope

---

assignments/mg-dts002/assign.diagnostics.json
policies/diagnostics/policy.json

Authorization rule id may need to be the full resource id including /subscriptions even though documentation suggests /provider will work.
Testing seems to suggest otherwise.

DTSPO-5695 - Remove eventHubName

---

assignments/mgmt-groups/mg-dts002/assign.diagnostics.json

To be merged when SecOps have confirmed that logs are being received by Splunk with the current subscriptions that are set up to forward activity logs to the event hubs.

DTSPO-5958 - Adding policy assignment for mgmt group

---

assignments/subscriptions/1497c3d7-ab6d-4bb7-8a10-b51d03189ee3/assign.tagging.json
assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json
assignments/subscriptions/1c4f0704-a29e-403d-b719-b90c34ef14c9/assign.tagging.json
assignments/subscriptions/62864d44-5da9-4ae9-89e7-0cf33942fa09/assign.tagging.json
assignments/subscriptions/7a4e3bd5-ae3a-4d0c-b441-2188fee3ff1c/assign.tagging.json
assignments/subscriptions/8a07fdcd-6abd-48b3-ad88-ff737a4b9e3c/assign.tagging.json
assignments/subscriptions/8b6ea922-0862-443e-af15-6056e1c9b9a4/assign.tagging.json
assignments/subscriptions/96c274ce-846d-4e48-89a7-d528432298a7/assign.tagging.json
assignments/subscriptions/d025fece-ce99-4df2-b7a9-b649d3ff2060/assign.tagging.json

Changing policy assignment enforcement from `DoNotEnforce` to `Default` which means tagging will now be enforced on create and update of resources on all non prod environments on CFT.
```
[ ] Yes
[x ] No
```

tagging policy enforcement on nonprod environments

---

assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.tagging.json

I created a resource group where I can create test workbooks in it. At the moment Azure doesn't allow me to create it under any sandbox Resource group because of tag enforcement, however I get an error when I try adding tags to resources "Kind not supported".
Reason: Workbooks don't allow you to create tags (despite the setting being available, I get an error "Kind not supported").
Workaround is: 
1. Create test resource group in sandbox subscription DCD-CFT-Sandbox (done manually)
2. Add test resource group to noScopes so there is no tagging policy evaluation (this PR).
```
[ ] Yes
[ x] No
```

exclusion for test resource group to create Workbooks

---

assignments/mgmt-groups/mg-dts002/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-9094
Excludes `AzureBackupRG_uksouth_1` in the from the tagging policy in place so backups generated by a Recovery Services Vault can succeed.
```
[ ] Yes
[ ] No
```

Exclude auto-generated azure backup resource group from tagging policy

---

assignments/mgmt-groups/mg-dts002/assign.tagging.json
assignments/subscriptions/3eec5bde-7feb-4566-bfb6-805df6e10b90/assign.tagging.json
assignments/subscriptions/5ca62022-6aa2-4cee-aaa7-e7536c8d566c/assign.tagging.json
assignments/subscriptions/74dacd4f-a248-45bb-a2f0-af700dc4cf68/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-9094
Adds tagging policy exclusions for the resource groups auto-generated by the Azure Recovery Service Vaults in SDS PROD and SDS STG subscriptions.
```
[ ] Yes
[ ] No
```

DTSPO-9094 exclude backup resource groups from SDS STG and PROD

---

assignments/mgmt-groups/mg-dts002/assign.tagging.json

Temp removal of PRE RG pre-sbox from tagging policy as it is failing.
This is to test the use of Azure SQL PaaS with PowerApps.
https://tools.hmcts.net/jira/browse/S28-744
Temp change to complete testing of Azure SQL.
```
[ ] Yes
[X] No
```

Remove the PRE RG in SBox from tagging policy

---

.github/workflows/manage-azure-policy.yml
README.md
custom_role.json

- Added some info on the permissions needed for the github workflow
- Reverting back to using the mg variable instead of a hard-coded value
```
[ ] Yes
[x] No
```

DTSPO-9985 - update README and use mg variable

---

assignments/subscriptions/17390ec1-5a5e-4a20-afb3-38d8d726ae45/assign.tagging.json
assignments/subscriptions/ae75b9fb-7d34-4112-82ff-64bd3855ce27/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-11753
Exclude Martha VM's from tagging policy to enable backups to be created
```
[ ] Yes
[ X] No
```

Exclude-Martha-VMs-To-Enable-Backups

---

assignments/subscriptions/bf308a5c-0624-4334-8ff8-8dca9fd43783/assign.tagging.json

testing out fleet manager but AKS doesn't propagate tags properly

Disable policy on RG for POC

---

assignments/subscriptions/1497c3d7-ab6d-4bb7-8a10-b51d03189ee3/assign.tagging.json

data migration services doesn't work with enforced tags, it tries to create a nic without copying tags

Disable tagging policy on timj-db-migrate-rg

---

policies/allowed_regions/policy.json

N/A
Exclude B2C tenants from the location policy, as they cannot be placed in UKSouth.
```
[ ] Yes
[x] No
```

fix: exclude B2C tenants from location policy

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

https://tools.hmcts.net/jira/browse/RWA-2691
Our jenkins infra build is failing due to a policy violation on location.  It is expecting UK South but we have a location of Wester Europe.  Our apps have all been live for some time so it would be difficult to change this now so I have suggested here we had our resources to the exemption list as others have.  I have added it for all envs since I assume it will fail elsewhere for the same reason.
Let us know if there's an alternative.
This is the build: https://build.platform.hmcts.net/view/WA/job/HMCTS_j_to_z/job/wa-shared-infrastructure/job/ithc/21/console

Adding wa appinsight resources to exemption list for location.

---

assignments/subscriptions/1baf5470-1c3e-40d3-a6f7-74bfbce4b348/assign.tagging.json

https://tools.hmcts.net/jira/browse/DTSPO-14926
This is only for test purpose this will be removed after test. The resources need to be excluded from policy deny effects for normal operation. Resources type Microsoft.Network/networkIntentPolicie. 
```
[ ] Yes
[x ] No
```

Exclude Resoure Group from policy for Azure SQL instance

---

policies/expires-after-tagging/policy.json
policies/tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-14926
Exclude SQL MI Security Alter Policies from tagging and expires after policies, these resources can't be tagged and are deployed automatically when you provision as SQL MI.
```
[ ] Yes
[x] No
```

fix: excluded SQLMI security alert policies from tagging and expiresAfter policies

---

policies/tagging/policy.json

Portal, CLI and powershell don't support tagging them.
Needs to be done via REST API or ARM
Lets remove the requirement

DTSPO-15235 Exclude VM extensions from tagging requirements

---

policies/expires-after-tagging/policy.json
policies/tagging/policy.json

When trying to create new frontdoor using portal or using powershell script, there is no way we can input tags for the WAF policies hence excluded them
```
[ ] Yes
[ X] No
```

excluded fw policies from tagging and expireafter

---

assignments/mgmt-groups/mg-HMCTS/assign.copy.rg.required.tags.json
assignments/mgmt-groups/mg-cft-sandbox/assign.copy.expireafter.tag.json
assignments/mgmt-groups/mg-platform-sandbox/assign.copy.expireafter.tag.json
assignments/mgmt-groups/mg-sds-sandbox/assign.copy.expireafter.tag.json
assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.copy.expireafter.tag.sandbox.json

After applying new copy tags policy, it failed to rollout because assignment name was too long. 
https://github.com/hmcts/azure-policy/actions/runs/6743864187/job/18332595163

fix policy assignment name length must not exceed

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

n/a
Deleting some old SecOps VM's and hit an issue with the SKU VM Policy. Need to remove the scope so these VM's can be removed

Removing the VM SKU policy from sec ops groups so they can be deleted

---

policies/allowed_regions/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-15909
While migrating App insights, we have noticed quite a few app insights are deployed on West Europe and region policy blocking us to update it so adding app insight as exception to see if we can avoid this block.

DTSPO-15909 - allow app insight to all region

---

policies/allowed_regions/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-16273
Revert a change that AppInsight component added to excludedResourceTypes. The change was made in this PR
https://github.com/hmcts/azure-policy/pull/304

DTSPO-16273 Revert a change that AppInsight component added to excludedResourceTypes

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

https://tools.hmcts.net/jira/browse/DTSPO-17130
Justification:
```
Hi Alex,
Are we able to please increase the RAM allocation on prddartsmigora01 to 64GB, but leave the CPU count at 4.
Reason being, we need to increase resource available to help with the performance of the Oracle DB on that server, without increasing the CPU core count which is how the Oracle licencing is determined.
We can’t use the current PlatOps approved templates as this would result in an increased CPU count, and that will incur significant licencing cost we don’t have approved.
Thanks,
Sean Bulley
Technical Architect
```

feat: added exclusion for darts-migration-prod-rg

---

assignments/mgmt-groups/mg-HMCTS/assign.tagging.json
assignments/mgmt-groups/mg-sds-sandbox/assign.expiresaftertag.json

https://tools.hmcts.net/jira/browse/DTSPO-16138
Temporarily exclude resource group from tagging policy so deleted keyvault can be restored and pipeline errors fixed
Pipeline errors need fixed so hub-terraform-infra pipeline is unblocked. Currently failing due to missing dependency

DTSPO-16138 - Temporary exclude for tagging cvp sbox rg

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_regions.json

https://tools.hmcts.net/jira/browse/DTSPO-17544
Add exclusion to allowed regions policy so I can deploy a test APIM instance to my test resource group
This is to test if an APIM instance more closely located to Slack's datacentres will help the incident bot
Will be reverted after testing

DTSPO-17544 - Exclude test rg from allowed regions policy

---

policies/tagging/policy.json

https://tools.hmcts.net/jira/browse/DTSPO-19515
Tagging policy blocks deployment of eventHub security resource for this story.

Adding new resource type to tagging exemption: Microsoft.Security/automations

---

assignments/subscriptions/b72ab7b7-723f-4b18-b6f6-03b0f2c6a1bb/assign.keyvault_diagnostics_moj.json
policies/keyvault/policy.json

Trying to get parameter name changes to take effect **without** updating profileNames and making more cleanup
This has been tested in sbox and correctly performs a new compliance check and remediation of resources to get the new eventhub name

Update policy to add existence condition

---

assignments/mgmt-groups/mg-HMCTS/assign.allowed_disk_sku.json
assignments/mgmt-groups/mg-HMCTS/assign.allowed_vm_sku.json

Jira link
https://tools.hmcts.net/jira/browse/DTSPO-23913
Change description
Added exception for Atlassian prod resource group so that we can restore the VMs as the VMs are different sizes.
Checklist
[x] commit messages are meaningful and follow good commit message guidelines
[ ] README and other documentation has been updated / added (if needed)
[ ] tests have been updated / new tests has been added (if needed)
[ ] Does this PR introduce a breaking change

DTSPO-23913 - adding exception for atlassian prod build

---

assignments/subscriptions/d24c931e-2e6d-4508-8583-85ac42715580/assign.nsg_diagnostics_glimr-rg-dev.json

This PR adds a new policy assignment for the NSG diagnostics policy (`HMCTSNSGDiagnostic`) to support the GLIMR development environment.
- ✅ Added NSG diagnostics policy assignment for subscription `d24c931e-2e6d-4508-8583-85ac42715580`
- ✅ Scoped assignment to `glimr-rg-dev` resource group only
- ✅ Configured to forward NSG logs to SOC Event Hub
- ✅ Uses existing SOC managed identity for Event Hub access
- **Policy**: `HMCTSNSGDiagnostic` (Diagnostic Settings for NSG to SOC)
- **Scope**: Resource group level - `/subscriptions/d24c931e-2e6d-4508-8583-85ac42715580/resourceGroups/glimr-rg-dev`
- **Event Hub**: `network-security-group` in SOC Event Hub namespace
- **Profile**: `NSG-SOC-Prod-GLIMR`
- Only affects Network Security Groups created within the `glimr-rg-dev` resource group
- …

feat: Add NSG diagnostics policy assignment for GLIMR development
